-- =============================================================================
-- DBMS Name      :    SQL Server
-- Script Name    :    update_fact_salessummary
-- Description    :    Update the fact table fact_salessummary
-- Generated by   :    WhereScape RED Version 8.6.6.1 (build 220216-231917)
-- Generated for  :    Amit Shah
-- Generated on   :    Friday, May 20, 2022 at 23:54:42
-- Author         :    Amit Shah
-- =============================================================================
-- Notes / History
--
CREATE PROCEDURE dbo.update_fact_salessummary
  @p_sequence         integer
, @p_job_name         varchar(256)
, @p_task_name        varchar(256)
, @p_job_id           integer
, @p_task_id          integer
, @p_return_msg       varchar(1024) OUTPUT
, @p_status           integer       OUTPUT
AS
  SET XACT_ABORT OFF  -- Turn off auto abort on errors
  SET NOCOUNT ON      -- Turn off row count messages
  --=====================================================
  -- Control variables used in most programs
  --=====================================================
  DECLARE
    @v_msgtext         varchar(1024) -- Text for audit_trail
  , @v_sql             nvarchar(255) -- Text for SQL statements
  , @v_set             integer       -- commit set
  , @v_analyze_flag    integer       -- analyze flag
  , @v_step            integer       -- return code
  , @v_update_count    integer       -- no of records updated
  , @v_insert_count    integer       -- no of records inserted
  , @v_delete_count    integer       -- no of records deleted
  , @v_count           integer       -- General counter
  , @v_db_code         varchar(10)   -- Database error code
  , @v_db_msg          varchar(1024) -- Database error message
  --=====================================================
  -- General Variables
  --=====================================================
  DECLARE
    @v_return_status   integer       -- Update result status
  , @v_getkey_status   integer       -- GetKey procedure status
  , @v_row_count       integer       -- General row count
  , @v_truncate_date   datetime      -- Used to set date to midnight
  --=====================================================
  -- MAIN
  --=====================================================
  SELECT @v_step = 0
  BEGIN TRY
  -- Set initial variable values
  SELECT
    @v_set          = 0
  , @v_analyze_flag = 0
  , @v_step         = 1
  , @v_update_count = 0
  , @v_insert_count = 0
  , @v_delete_count = 0
  
  --=======================================================
  -- Delete any records that we will be replacing
  --=======================================================
  BEGIN TRANSACTION
    DELETE FROM {{ ref('fact_salessummary')}}
    WHERE fact_salessummary.salesorderid IN ( SELECT DISTINCT stage_salessummary.salesorderid FROM {{ ref('stage_salessummary')}} stage_salessummary )
    SELECT @v_delete_count = @@ROWCOUNT
  COMMIT
  
  --=======================================================
  -- Insert all records into the fact table
  --=======================================================
  SET @v_step = 100
  BEGIN TRANSACTION
    INSERT INTO {{ ref('fact_salessummary')}} WITH ( TABLOCK )
    ( dim_order_date_key
    , salesorderid
    , orderdate
    , subtotal
    , taxamt
    , freight
    , totaldue
    , orderqty
    , linetotal
    , dss_create_time
    , dss_update_time
    )
    SELECT
      dim_order_date_key
    , salesorderid
    , orderdate
    , subtotal
    , taxamt
    , freight
    , totaldue
    , orderqty
    , linetotal
    , GETDATE()
    , GETDATE()
    FROM   {{ ref('stage_salessummary')}}
    
    SELECT @v_insert_count = @@ROWCOUNT
  COMMIT
  --=====================================================
  -- All Done report the results
  --=====================================================
  -- WsWrkTask(job,task,seq,insert,update,replace,delete,discard,reject,error)
  EXEC dbo.WsWrkTask @p_job_id, @p_task_id, @p_sequence,
    @v_insert_count,0,0,@v_delete_count,0,0,0
  SET @v_step = 200
  IF @v_delete_count > 0
  BEGIN
    SET @p_status = 1
    SET @p_return_msg = 'fact_salessummary updated. '
      + CONVERT(varchar,@v_insert_count) + ' new records. '
      + CONVERT(varchar,@v_delete_count) + ' records deleted.'
  END
  ELSE
  BEGIN
    SET @p_status = 1
    SET @p_return_msg = 'fact_salessummary updated. '
      + CONVERT(varchar,@v_insert_count) + ' new records. '
  END
  RETURN 0
  END TRY
  BEGIN CATCH
    SET @p_status = -2
    SET @p_return_msg = SUBSTRING('fact_salessummary update FAILED with error '
      + CONVERT(varchar,IFNULL(ERROR_NUMBER(),0))
      + ' Step ' + CONVERT(varchar,IFNULL(@v_step,0))
      + '. Error Msg: ' + ERROR_MESSAGE(),1,1023)
  END CATCH
  IF XACT_STATE() <> 0
  BEGIN
    ROLLBACK TRANSACTION
  END
  RETURN 0
